app = "cashlogix-backend"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[build]
  builder = "paketobuildpacks/builder:base"
